namespace Protocol
{
	public enum PResult
	{
		SUCCESS,

		ACCOUNT_EXIST,
		ACCOUNT_NOT_FOUND,
		ACCOUNT_INVAILD,
		PASSWORD_INVALID,
		ACCOUNT_PASSWORD_NOT_MATCH,
		ACCOUNT_ONLINE,
		ACCOUNT_OFFLINE,

		USER_EXIST,
		USER_NOT_FOUND,
		USER_ONLINE,
		USER_OFFLINE,

		LEAVE_HALL_FAILED,
		ENTER_HALL_FAILED,

		ROOM_CREATE_FAILED,
		ROOM_NOR_FOUND,
		USER_IN_ROOM,
		USER_NOT_IN_ROOM,
		USER_IN_TEAM,
		USER_NOT_IN_TEAM,
		TEAM_FULL,
		ROOM_FULL,
		ROOM_NOT_MATCH,
		REMOVE_USER_FROM_ROOM_FAILED,
		ROOM_LOCKED,
		NOT_ALL_USER_READY,
		NOT_ENOUGTH_USERS,
		USER_READY,
		USER_NOT_READY,
		ROOM_NO_PERMISSIONS,
		CHANGE_MAP_FAILED,

		ENTER_BATTLE_FAILED,
		CREATE_BATTLE_FAILED,
		USER_NOT_INT_BATTLE,

		STEPLOCKER_NOT_FOUND,
		WAIT_FOR_USER_BATTLE_CREATED,
		WAIT_FOR_USER_ENDED
	}
}